import * as Cosmos from "../common";

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionRequest extends Cosmos.FunctionRequest {
    readonly payload: GoogleGroupsMembershipsStudentsCalculateAllFunctionRequestPayload;
}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionResponse extends Cosmos.FunctionResponse {
    readonly payload: GoogleGroupsMembershipsStudentsCalculateAllFunctionResponsePayload;
}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionLogObject extends Cosmos.FunctionLogObject {
    readonly payload: GoogleGroupsMembershipsStudentsCalculateAllFunctionResponsePayload;
}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionCallbackMessage extends Cosmos.FunctionCallbackMessage {}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionInvocationEvent extends Cosmos.FunctionInvocationEvent {
    readonly data: GoogleGroupsMembershipsStudentsCalculateAllFunctionInvocationEventPayload;
}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionRequestPayload extends Cosmos.FunctionRequestPayload {
    readonly schoolCode: string;
}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionResponsePayload extends Cosmos.FunctionResponsePayload {
}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionLogObjectPayload extends Cosmos.FunctionLogObjectPayload {}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionCallbackMessagePayload extends Cosmos.FunctionCallbackMessagePayload {}

interface GoogleGroupsMembershipsStudentsCalculateAllFunctionInvocationEventPayload extends Cosmos.FunctionInvocationEventPayload {}

export {
    GoogleGroupsMembershipsStudentsCalculateAllFunctionRequest,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionResponse,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionLogObject,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionCallbackMessage,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionInvocationEvent,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionRequestPayload,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionResponsePayload,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionLogObjectPayload,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionCallbackMessagePayload,
    GoogleGroupsMembershipsStudentsCalculateAllFunctionInvocationEventPayload
}
